version: "3.7"

services:
  postgres:
    container_name: carpool_postgres
    image: postgres:11
    environment:
      - "POSTGRES_PASSWORD=local"
      - "POSTGRES_USER=local"
      - "POSTGRES_DB=carpool"
    ports:
      - 5432:5432
  adminer:
    container_name: carpool_adminer
    image: wodby/adminer:4.7
    ports:
      - 9000:9000
    environment:
      - "ADMINER_DEFAULT_DB_DRIVER=pgsql"
      - "ADMINER_DEFAULT_DB_HOST=postgres"
      - "ADMINER_DEFAULT_DB_NAME=carpool"
